# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_auto_20160625_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatemediaurl',
            name='media_type',
            field=models.CharField(choices=[('youtube', 'YouTube')], max_length=8),
        ),
    ]
